### ISSUE TITLE
مشکلات که در هماهنگی فرم حروف به چشم می‌اید

### ISSUE THREAD

**Issue by zoghal** [aminabedi68/Estedad#1]
امین جان اگر اجازه بدید قصد دارم جهت بهتر شدن و هماهنگی بیشتر حروف‌ها در تایپ فیس تون نکاتی رو خدمتتون مطرح کنم؟ 
یا می‌تونید تو تلگرام هم انجامش بدیدم تا سریع تر میشه. من خیلی از یکسری فرم‌ها خوشم اومد حیف است که در تغییرات اون‌ها از دست بره :)

**Comment by aminabedi68** [comment]
سلام آقای سوزنچی، با کمال میل مشتاق بهره مندی از تجربیات شما هستم، من شماره شما رو ندارم ولی شماره خودمو انتهای این پست میذارم، هر وقت مایل بودین، من آمادم
۰۹۰۱۰۲۰۷۰۸۴

**Comment by aminabedi68** [comment]
صالح جان لطفا چک کنین :)))
