### ISSUE TITLE
الف مقصوره

### ISSUE THREAD

**Issue by parhizkari** [aminabedi68/Estedad#10]
سلام و عرض ادب و احترام خدمت جناب عابدی،
امکانش هست الف مقصوره را کمی کشیده‌تر نمایید تا بهتر قابل تشخیص باشد؟

**Comment by aminabedi68** [comment]
سلام، من به درستی متوجه نشدم، اگر منظورتون مد آ هست، کشیده کردنش به دلیل درگیری با سایر حروف(مثل ک و ...) و ایجاد شدن فضای خالی و ناهمگن بین اونها نتیجه خوبی نداره اما تو نسخه پنجم که در حال ساختش هستم این نکته رو در نظر گرفتم و کمی خواناتر شده نسبت به قبل
اگر منظور شما ارتفاع خود الف باشه نمیشه اینکار رو انجام داد چون کل فونت بر پایه همین ارتفاع تنظیم شده و همه چیز بهم میریزه
بسیار ممنون

**Comment by aminabedi68** [comment]
در نسخه پنجم تا حدودی برطرف شد
