### ISSUE TITLE
استفاده از قلم لاتین میخک به جای قلم لاتین استعداد

### ISSUE THREAD

**Issue by parhizkari** [aminabedi68/Estedad#11]
سلام و عرض ادب و احترام،
از قلم استعداد شما خیلی استفاده می‌کنم و از بابت طراحی و نشر رایگان آن از شما خیلی متشکرم، ولی چون قلم لاتین آن به نظرم خیلی با فرم شاد قلم استعداد سازگار نبود، الآن بابت متون انگلیسی در داخل متن فارسی مجبور شده‌ام قلم Cavolini را با قلم استعداد همراه کنم و مثلاً در فایل CSS خودم بنویسم:
font-family: Cavolini, Estedad;
در این یکی دو روزه که متوجه شدم شما وب‌سایت دارید و با قلم‌های دیگرتان هم آشنا شدم، دیدم که گلیف‌هایی که برای انگلیسی قلم میخک ساخته‌اید با قلم استعداد خیلی خوب جفت می‌شود. حالا می‌خواستم ببینم آیا امکان دارد که:
   ۱. این گلیف‌های لاتین جایگزین گلیف‌های فعلی لاتین برای قلم استعداد هم بشود
   ۲. اگر نمی‌شود، آیا می‌شود گلیف‌های فارسی و لاتین دو قلم استعداد و میخک به صورت جداگانه هم عرضه شوند تا هر کسی بتواند گلیف‌های فارسی و لاتین آن دو را به سلیقه‌ی خودش در کنار هم به کار ببرد؟
با تشکر

**Comment by aminabedi68** [comment]
سلام و خیلی ممنون.
1- گلیفهای لاتین هر فونتی مختص خود اون فونت طراحی شده و نمیشه برای قسنت لاتین یه فونت دیگه جایگزین بشه
2- بله، چرا که نه، پیشنهاد خوبیه
