### ISSUE TITLE
Tagging and Versioning Problem

### ISSUE THREAD

**Issue by molaeiali** [aminabedi68/Estedad#12]
Hi, First, thanks for the awsome font and your work

I am maintaining a package on Arch Linux AUR for some of your fonts [estedad-fonts](https://aur.archlinux.org/packages/estedad-fonts/) and [mikhak-fonts](https://aur.archlinux.org/packages/mikhak-fonts/)

Your recent release tags and changing font directories in releases without increasing or changing the version is making it hard for me (and possibly others) to keep doing this work, my question is: Not increasing the point number of the release and retagging with the same version again is for what? Any specific reason for that? to be more clear, why 5.0(2) and not 5.1?

It would be great to keep the zip URL consistent with the version
`${url}/releases/download/${pkgver}/Estedad-V${pkgver}.zip"`

With this (2) I should check manually for the release zip URL and add a (2) after $pkgver to generate the correct URL.

Again thanks for your great work again :)
This problem also exists on Mikhak font, but I will **not** open another issue there <3

**Comment by aminabedi68** [comment]
hi @molaeiali thank you for the issue and your works on Arch Linux AUR packages.
some people said me it would be great to have FD(Farsi Digits instead Latin) versions in 'Estedad' and 'Mikhak' repo and release packages, they need these versions to use in Farsi websites. so, there is no major updates and you don't have to update.

> It would be great to keep the zip URL consistent with the version
> `${url}/releases/download/${pkgver}/Estedad-V${pkgver}.zip"`

OK, I will consider this in the future releases.
