### ISSUE TITLE
Some bugs and requests

### ISSUE THREAD

**Issue by cssobral2013** [aminabedi68/Estedad#13]
- The K/k without diacritics looks different than with diacritics;
 - The cedilla in some letters (more precisely, K/kcedilla, G/gcedilla, L/lcedilla, N/ncedilla, R/rcedilla, and D/dcedilla) should be comma-shaped (such as in S/scommaaccent and T/tcommaaccent);
 - As a sidenote above, the gcedilla should look like a g with an inverted comma above.

**Comment by aminabedi68** [comment]
hi @cssobral2013 
 
>     * The K/k without diacritics looks different than with diacritics;
Latin section has no marks at all so maybe the issue is about that(if I'm wrong please reply with captured photos), I'll solve the problem in the next version.

>     * The cedilla in some letters (more precisely, K/kcedilla, G/gcedilla, L/lcedilla, N/ncedilla, R/rcedilla, and D/dcedilla) should be comma-shaped (such as in S/scommaaccent and T/tcommaaccent);
>     * As a sidenote above, the gcedilla should look like a g with an inverted comma above.
I'll check, thank you.

**Comment by cssobral2013** [comment]
@aminabedi68 - See the picture below I made with FontCreator on Wine (because I use Linux). All other glyphs mentioned on this issue display it.
![Picture 1](https://user-images.githubusercontent.com/19995437/113464455-2dd9e700-9403-11eb-82dd-16471fedbf3a.png)
As you can see on the right, the K/k without any diacritic is different from a K/kcedilla (on top left), for example. Also, on next picture, the cedilla on letters mentioned in OP should look like this (example on S/scommaaccent):
![Picture 2](https://user-images.githubusercontent.com/19995437/113464590-2535e080-9404-11eb-9a14-bbaed0015db8.png)

**Comment by aminabedi68** [comment]
I get it! thank you 👍
