### ISSUE TITLE
Oldstyle figures -- slashed zero only?

### ISSUE THREAD

**Issue by a-mg** [aminabedi68/Estedad#14]
While there are both slashed and unslashed zero variants for the lining figures, the oldstyle figures only have a slashed zero. This makes it difficult to use oldstyle figures in text, since the slashed zero looks so technical. Do you have plans to add an unslashed oldstyle zero?

I really love the v5 Latin alphabet design, so this would be a great addition for me!

**Comment by aminabedi68** [comment]
hello @a-mg sorry for delay
thank you for the issue.
OK. I'll consider that in the next release.

**Comment by aminabedi68** [comment]
please check new release.
