### ISSUE TITLE
Preparing Estedad and Mikhak to Google Fonts

### ISSUE THREAD

**Issue by yanone** [aminabedi68/Estedad#16]
Hello,

I've been commissioned with onboarding Estedad and Mikhak to Google Fonts, so the following question applies to both typefaces.

I’m wondering how to proceed with this practically: Whether to make the changes necessary to meet our specifications and PR them back to you, or whether to fork the repository on continue from there.

As far as I can tell as the moment, the changes include:
* Copyright field in name table change to `Copyright 2015 The Estedad Project Authors (https://github.com/aminabedi68/Estedad)`
* Eliminate nested components
* Add `STAT` and `avar` tables
* `OS/2.fsSelection` bit 7 needs to be set (Use Typo metrics)
* Adjustments to vertical metrics
* Decompose transformed components
* Adjust width on non-breaking space glyph

I haven't looked at Mikhak yet, but I'm expecting a similar set of changes.

Please let me know whether you are comfortable with the proposed changes to your repo or not.

Thank you.

**Comment by aminabedi68** [comment]
hello @yanone , thank you.
I'll be glad to see Estedad and Mikhak typefaces on Google Fonts :)

> I’m wondering how to proceed with this practically: Whether to make the changes necessary to meet our specifications and PR them back to you, or whether to fork the repository on continue from there.

no offense, I prefer to control the project on my own(much easier that way for future updates), so if I can apply your requests by doing some modifications on the sources and applying post-process levels to the final font files(with python scripts, like [Mikhak ](https://github.com/aminabedi68/Mikhak)build process), you don't need neither PR nor fork, just open another issues! (it's OK if you want to create a few PRs to add/update some information without changing the sources, final ttf files and build process)


> Copyright field in name table change to `Copyright 2015 The Estedad Project Authors (https://github.com/aminabedi68/Estedad)`
> 
> Add `STAT` and `avar` tables
> 
> `OS/2.fsSelection` bit 7 needs to be set (Use Typo metrics)
> 
> Adjust width on non-breaking space glyph

OK  
  
<br/>

> Eliminate nested components

you mean `maxComponentDepth=1`?
  
<br/>

> Adjustments to vertical metrics

i should have the numbers!
  
<br/>

> Decompose transformed components

Estedad(and Mikhak) has no mirrored components, but maybe there are some scaled components, I should have a look.


<br/>
I have some tasks to do for Estedad(major update) and Mikhak(minor update) typefaces, so if we have a time limit, please let me know. thank you.

**Comment by yanone** [comment]
Okay, great. There's no time limit. I’ll get back to you with detailed reports about each of the typefaces, each in their own new issue, so I’m closing this issue right now.
Thank you
