### ISSUE TITLE
یه سوال در مورد نوع فونت

### ISSUE THREAD

**Issue by MahdiPishguy** [aminabedi68/Estedad#2]
سلام. ممنون بابت انتشار این فونت زیباتون یه سوال داشتم از اونجایی که آشنایی با فونت و اینها ندارم منظور از 
HelveticaLT-Light Glyphs

چی هستش؟

**Comment by aminabedi68** [comment]
سلام. ممنون از محبت شما. دو نوع از این فونت ساخته میشه، یک نوعش با حروف لاتین و یک نوع بدون حروف لاتین. 
منظور از این عبارت اشاره به نوع اول و اسم فونت لاتین هست، اگه با این فونت یه عبارت مخلوط فارسی و لاتین بنویسید برای نمایش قسمت لاتین به فونت نوع اول نیاز دارین. برای کاربردهای خاص تر ممکنه فونت نوع دوم که بدون قسمت لاتین و کم حجم تر هست بیشتر به درد بخوره
