### ISSUE TITLE
طراحی حروف (ل+ا)

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [aminabedi68/Estedad#21]
این قسمت در حروف (لا) میتونه روون‌تر وصل بشه

![Screenshot 2022-05-03 115021](https://user-images.githubusercontent.com/44550501/166417069-030f4eea-a8a6-497f-b1db-6b86ec4b1cd7.png)

**Comment by aminabedi68** [comment]
امتحان کرده بودم، توی وزنای پایین‌تر زیاد جالب نمیشه :/

**Comment by Ahmadhosseinbor** [comment]
> امتحان کرده بودم، توی وزنای پایین‌تر زیاد جالب نمیشه :/

این فقط یه پیشنهاد بود وگرنه طراحی شما مشکلی نداره، حالا که میبینم اگه اونطوری طراحی بشه شبیه فونت وزیرمتن میشه که این خوب نیست

**Comment by aminabedi68** [comment]
بله، ممنونم. پس من این ایشو رو میبندم.
