### ISSUE TITLE
مشکل در حرف (ے) در زبان اردو

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [aminabedi68/Estedad#22]
بهتره حرف (ے) در زبان اردو یه مقدار کشیده‌تر باشه

![Screenshot 2022-05-03 123607](https://user-images.githubusercontent.com/44550501/166421793-1a52a068-ff04-4f11-af38-1988ae3e4941.png)

**Comment by aminabedi68** [comment]
بله، حق با شماست باید کشیده‌تر بشه ولی یخورده کار opentype داره، چون با حروفی مثل «ی‍» یا حروف دیگه اگه حرکه‌های پایین داشته باشن تداخل پیش میاره.

**Comment by aminabedi68** [comment]
تو نسخۀ جدید یه ذره بهتر شده. امیدوارم کافی باشه
![firefox_nR8OjcJ8gx](https://user-images.githubusercontent.com/25493297/169559083-eb743fc8-8de9-444a-a7f7-775e14aa02fe.png)
من این ایشو رو فعلاً میبندم. چون حداقل به این زودیا کشیده‌تر از این نمیشه.
