### ISSUE TITLE
font-height یا line-height

### ISSUE THREAD

**Issue by ShahriarKh** [aminabedi68/Estedad#23]
توی صفحه‌ی تست نسخه‌ی متغیر، به نظرم line-height اشتباهی font-height نوشته شده.
![image](https://user-images.githubusercontent.com/31452340/167269297-f397a9be-c8d2-41b7-8a24-f6167a202cab.png)

**Comment by aminabedi68** [comment]
ممنونم، اصلاح شد 👍
