### ISSUE TITLE
فاصله خطوط

### ISSUE THREAD

**Issue by AbbasAlimi** [aminabedi68/Estedad#26]
سلام
ممنون بابت این فونت بسیار خوب
به نظرم فاصله خطوط زیاد است. به نظرم اگر فاصله خطوط حداقل مقدار ممکن باشد بهتر است چون در هر نوع استفاده از فونت می‌توان به راحتی فاصله خطوط را افزایش داد و فاصله‌ی کم مشکل‌ساز نیست ولی کاهش فاصله خطوط یا سخت است یا مشکل‌ساز.

**Comment by aminabedi68** [comment]
سلام، ممنونم.
راستش فاصلۀ خطوط  رو نمیشه کمتر کرد، توی آخرین نسخه یه ذره دستکاری کردم ولی بازم زیاده، چون googlefonts کمتر از اون رو نمیپذیره به خاطر اینکه گلیفهایی توی فونت وجود دارن که ممکنه با کم شدن حدود بالا و پایین به صورت بریده شده دیده بشن.
