### ISSUE TITLE
Add Alternate a

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [aminabedi68/Estedad#27]
![IMG_20220615_182218_490.jpg](https://user-images.githubusercontent.com/44550501/173844852-499647a6-7cc4-435d-99be-8f0573fc8e56.jpg)

**Comment by aminabedi68** [comment]
فکر خوبیه 👍

**Comment by aminabedi68** [comment]
توی نسخۀ جدید برای استایل ست چهارم ss04 اضافه شد.
