### ISSUE TITLE
جدا سازی فونت اعداد فارسی و اعداد انگلیسی [Feature Request]

### ISSUE THREAD

**Issue by amirmeimari** [aminabedi68/Estedad#5]
ممنونم فونت بسیار خوبی  هست.
فقط یک مشکلی که وجود داره این هست که برای اعداد فارسی و انگیسی فونت های جدا وجود داشته باشه خیلی بهتر میشه.
مثلا یک فونت FaNum باشه و یکی فقط با اعداد انگیسی.
مثل فونت دانا و ایران سنس که این فیچر رو دارند.

الان برای وب باید برای هر عددی که میخوام فارسی نمایش بدم یه فانکشن بفنویسم و نمایش اون رو به کاراکتر های فرسی تغییر بدم. اگه فونت این رو ساپورت کنه همه این ها حل میشه :)

**Comment by aminabedi68** [comment]
سلام، خواهش میکنم :) تو نسخۀ چهارم اعداد انگلیسی فارسی شده و نسخۀ بدون قسمت لاتین هم اضافه شدن، شما چک کردین؟

**Comment by dehghani-mehdi** [comment]
@aminabedi68 
کدوم نسخه بدون قسمت لاتین هست؟ ندیدم جایی که بشه دانلود کرد
