### ISSUE TITLE
The multiplication sign glyph (id 143) is malformed with non-default weights

### ISSUE THREAD

**Issue by RazrFalcon** [aminabedi68/Estedad#6]
Rendered with FreeType2.

wght=900

![900](https://user-images.githubusercontent.com/725494/75790787-5b71de00-5d74-11ea-9baa-22efb6f59d47.png)

wght=500

![500](https://user-images.githubusercontent.com/725494/75790802-5f056500-5d74-11ea-9ce7-1c9122a2aef4.png)

wght=100

![100](https://user-images.githubusercontent.com/725494/75790810-62005580-5d74-11ea-98da-0038b84d2916.png)

**Comment by aminabedi68** [comment]
Fixed in the new release, thank you.
