### ISSUE TITLE
نمایش نادرست چند ی پشت سر هم در اینک‌اسکیپ

### ISSUE THREAD

**Issue by ahangarha** [aminabedi68/Estedad#7]
<div dir=rtl>
سلام

با نوشتن چند ی پشت سر هم در اینک‌اسکیپ چنین مشکلی ایجاد می‌شود:

![image](https://user-images.githubusercontent.com/11241315/78460982-cfd4cf80-76da-11ea-8afe-f1850077861d.png)

**Comment by aminabedi68** [comment]
سلام
این مشکل مربوط به خود اینک‌اسکیپ بود که اینجا گزارش شده:
https://gitlab.com/inkscape/inkscape/-/issues/469
و تو نسخه‌های فعلی(نسخۀ شماره 1 رسمی به بعد) روی ویندوز مشکلی مشاهده نمیشه:
![inkscape_4oral4I7Ta](https://user-images.githubusercontent.com/25493297/86914244-35e74d80-c135-11ea-897e-602158cfe5a3.png)
به هر حال ویژگی‌ای که باعث بروز این مشکل تو اینک‌اسکیپهای قبلی شده تو نسحۀ بعدی حذف خواهد شد، چون ظاهرا ادوبی با این قضیه [مشکل ](https://github.com/aminabedi68/Estedad/issues/8)داره
