### ISSUE TITLE
درخواست نسخه‌ی رنگی قلم

### ISSUE THREAD

**Issue by parhizkari** [aminabedi68/Estedad#9]
سلام آقای عابدی،
من عاشق زیبایی و خوانایی قلم استعداد شما هستم، خودم هم یک مقدار برای دل خودم قلم درست کرده‌ام که البته حرفه‌ای نیستند.
می‌خواستم ببینم آیا امکانش هست برایتان که نسخه‌ی رنگی این قلم زیبا را هم فراهم کنید تا حرکات فتحه و کسره و ضمّه و سکون و تشدید و تنوین‌ها مثلاً آبی یا قرمز باشند؟ شاید اگر نقاط حروف هم رنگی شوند خوب باشد، مثل کاری که در نقاشی‌خط‌ها انجام می‌دهند. اگر نه آیا به من اجازه می‌دهید این کار را بکنم؟
من برای این کار از برنامه‌ی scfbuild استفاده می‌کنم.

**Comment by aminabedi68** [comment]
سلام و خیلی ممنون از محبت شما
اهداف زیادی برای توسعه بیشتر فونت استعداد وجود داره ولی ساخت نسخۀ رنگی یکی از اونا نیست
اگر دوست دارین این کار رو انجام بدین برای من هم جالب و جذابه ولی پیشنهاد میکنم بعد از بروزرسانی نسخۀ پنجم این کار رو شروع کنین
اگر تونستین از تکنولوژی
COLR/CPAL
استفاده کنین بهتر میشه چون باهاش میشه فونت متغیر هم ساخت
موفق باشین

**Comment by parhizkari** [comment]
سلام آقای عابدی عزیز،
گلیف‌ها را توسط fontforge به صورت فایل‌های svg مجزا صادر کردم و بعد حرکات حروف را رنگی کردم و بعد از کمی تغییرات نامرتبط (_جایگزینی گلیف‌های انگلیسی از قلم میخک شما، و کشیدن جزئی الف‌مقصوره‌ها_) قلم رنگی را ساختم، اما نتیجه ناامید کننده بود. ظاهراً برنامه‌ای که برای تولید قلم رنگی استفاده می‌کنم فقط برای قلم‌های ابتدایی بدون تنظیمات زیاد درست کار کند.
[font.zip](https://github.com/aminabedi68/Estedad/files/5140078/font.zip)

**Comment by aminabedi68** [comment]
تبدیل به یه اثر هنری شده 😂

![firefox_2020-08-28_21-50-50](https://user-images.githubusercontent.com/25493297/91595352-a31aa080-e978-11ea-95ab-37bfe900f10a.png)

ظاهرا با این روش نمیشه فونتی که از اپن تایپ استفاده میکنه رو رنگی کرد

**Comment by zoghal** [comment]
چه شاهکاری شده :))
